# Generated by Django 3.1.7 on 2021-03-18 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255)),
                ('About_company', models.TextField()),
                ('Company_link', models.URLField(max_length=255)),
                ('Jobrole', models.CharField(max_length=255)),
                ('Job_responsilities', models.TextField()),
                ('Job_Salary', models.FloatField(max_length=5)),
                ('Eligibility_cgpa', models.FloatField(max_length=3)),
                ('Eligibility_branches', models.TextField()),
                ('Eligible_Passedout_Batchs', models.CharField(max_length=255)),
                ('Eligibility_education_gap', models.IntegerField()),
                ('application_start_date', models.DateField(null=True)),
                ('application_end_date', models.DateField(null=True)),
                ('not_eligible', models.IntegerField(default=0)),
                ('not_attended', models.IntegerField(default=0)),
                ('written_selects', models.IntegerField(default=0)),
                ('tr_selects', models.IntegerField(default=0)),
                ('final_selects', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='materials/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_image', models.FileField(default='https://th.bing.com/th/id/OIP.ARJrx9vRGJcvJDizj8UgPgHaGR?w=259&h=220&c=7&o=5&pid=1.7', upload_to='StudentPics/')),
                ('student_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('tenth', models.CharField(max_length=255)),
                ('twelve', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(max_length=3)),
                ('no_backlog', models.IntegerField()),
                ('c_backlog', models.IntegerField()),
                ('branch', models.CharField(blank=True, choices=[('1', 'ECE'), ('2', 'CES'), ('3', 'EEE'), ('4', 'ME')], max_length=3)),
                ('Placement_status', models.BooleanField(default=False)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Title', models.CharField(blank=True, max_length=255)),
                ('Post_Subject', models.CharField(blank=True, max_length=255)),
                ('Post_body', models.TextField(blank=True)),
                ('Post_CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Post_Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
