# Generated by Django 3.1.7 on 2021-03-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
