# Generated by Django 3.1.7 on 2021-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAccount', '0004_auto_20210318_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='StudentPassword',
            field=models.CharField(default='klef123', max_length=50),
        ),
    ]
